# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Siri' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Siri
  pod 'JSONJoy-Swift', '~> 1.0.1'
  pod 'Alamofire', '~> 3.5.0'
  pod 'RecastAI'
  pod 'ForecastIO', :git => 'https://github.com/sxg/ForecastIO.git', :branch => 'swift2.3'
  pod 'JSQMessagesViewController'
  pod 'syncano-ios'  


end
